apiVersion: apps/v1
kind: Deployment
metadata:
  name: compliance-frontend
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "compliance.labels" . | nindent 4 }}
    tier: frontend
spec:
  replicas: {{ .Values.replicaCount.frontend }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      {{- include "compliance.selectorLabels" . | nindent 6 }}
      tier: frontend
  template:
    metadata:
      labels:
        {{- include "compliance.selectorLabels" . | nindent 8 }}
        tier: frontend
    spec:
      {{- if eq .Values.podSecurity.level "restricted" }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
        seccompProfile:
          type: RuntimeDefault
      {{- end }}
      containers:
        - name: frontend
          image: {{ include "compliance.frontendImage" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          {{- if eq .Values.podSecurity.level "restricted" }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 101
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
          {{- end }}
          env:
            - name: API_URL
              value: "/api"
          readinessProbe:
            httpGet:
              path: /nginx-health
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /nginx-health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            {{- toYaml .Values.resources.frontend | nindent 12 }}
          {{- if eq .Values.podSecurity.level "restricted" }}
          volumeMounts:
            - name: nginx-cache
              mountPath: /var/cache/nginx
            - name: nginx-run
              mountPath: /var/run
            - name: nginx-tmp
              mountPath: /tmp
          {{- end }}
      {{- if eq .Values.podSecurity.level "restricted" }}
      volumes:
        - name: nginx-cache
          emptyDir: {}
        - name: nginx-run
          emptyDir: {}
        - name: nginx-tmp
          emptyDir: {}
      {{- end }}
