apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "compliance.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USER: {{ .Values.database.credentials.user }}
  DB_PASSWORD: {{ .Values.database.credentials.password }}
  DB_NAME: {{ .Values.database.credentials.name }}
