apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "compliance.labels" . | nindent 4 }}
    tier: frontend
spec:
  type: ClusterIP
  selector:
    {{- include "compliance.selectorLabels" . | nindent 4 }}
    tier: frontend
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
