apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "compliance.labels" . | nindent 4 }}
    tier: api
spec:
  type: ClusterIP
  selector:
    {{- include "compliance.selectorLabels" . | nindent 4 }}
    tier: api
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
