apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "compliance.labels" . | nindent 4 }}
    tier: db
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- include "compliance.selectorLabels" . | nindent 4 }}
    tier: db
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
